// client/src/pages/login.tsx
import signuppage from "../assets/img/signuppage.svg"


const LogIn = () => {
    return (
        <section className="bg-white">
          <div className="grid grid-cols-1 lg:grid-cols-2">
            <div className="flex items-center justify-center px-4 py-10 bg-white sm:px-6 lg:px-8 sm:py-16 lg:py-24">
              <div className="xl:w-full xl:max-w-sm 2xl:max-w-md xl:mx-auto">
                <h2 className="text-3xl font-bold leading-tight text-black sm:text-4xl">
                  Sign in to Celebration
                </h2>
                <p className="mt-2 text-base text-gray-600">
                  Don’t have an account?{" "}
                  <a
                    href="#"
                    title=""
                    className="font-medium text-blue-600 transition-all duration-200 hover:text-blue-700 hover:underline focus:text-blue-700"
                  >
                    Create a free account
                  </a>
                </p>
    
                <form action="#" method="POST" className="mt-8">
                  <div className="space-y-5">
                    <div>
                      <label
                        htmlFor=""
                        className="text-base font-medium text-gray-900 text-left"
                      >
                        {" "}
                        Email address{" "}
                      </label>
                      <div className="mt-2.5">
                        <input
                          type="email"
                          name=""
                          id=""
                          placeholder="Enter email to get started"
                          className="block w-full p-4 text-black placeholder-gray-500 transition-all duration-200 border border-gray-200 rounded-md bg-gray-50 focus:outline-none focus:border-blue-600 focus:bg-white caret-blue-600"
                        />
                      </div>
                    </div>
    
                    <div>
                      <div className="flex items-center justify-between">
                        <label
                          htmlFor=""
                          className="text-base font-medium text-gray-900"
                        >
                          {" "}
                          Password{" "}
                        </label>
    
                        <a
                          href="#"
                          title=""
                          className="text-sm font-medium text-blue-600 hover:underline hover:text-blue-700 focus:text-blue-700"
                        >
                          {" "}
                          Forgot password?{" "}
                        </a>
                      </div>
                      <div className="mt-2.5">
                        <input
                          type="password"
                          name=""
                          id=""
                          placeholder="Enter your password"
                          className="block w-full p-4 text-black placeholder-gray-500 transition-all duration-200 border border-gray-200 rounded-md bg-gray-50 focus:outline-none focus:border-blue-600 focus:bg-white caret-blue-600"
                        />
                      </div>
                    </div>
    
                    <div>
                      <button
                        type="submit"
                        className="inline-flex items-center justify-center w-full px-4 py-4 text-base font-semibold text-white transition-all duration-200 bg-blue-600 border border-transparent rounded-md focus:outline-none hover:bg-blue-700 focus:bg-blue-700"
                      >
                        Log in
                      </button>
                    </div>
                  </div>
                </form>
    
                <div className="mt-3 space-y-3">
                  <button
                    type="button"
                    className="relative inline-flex items-center justify-center w-full px-4 py-4 text-base font-semibold text-gray-700 transition-all duration-200 bg-white border-2 border-gray-200 rounded-md hover:bg-gray-100 focus:bg-gray-100 hover:text-black focus:text-black focus:outline-none"
                  >
                    <div className="absolute inset-y-0 left-0 p-4">
                      <svg
                        className="w-6 h-6 text-rose-500"
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        fill="currentColor"
                      >
                        <path d="M20.283 10.356h-8.327v3.451h4.792c-.446 2.193-2.313 3.453-4.792 3.453a5.27 5.27 0 0 1-5.279-5.28 5.27 5.27 0 0 1 5.279-5.279c1.259 0 2.397.447 3.29 1.178l2.6-2.599c-1.584-1.381-3.615-2.233-5.89-2.233a8.908 8.908 0 0 0-8.934 8.934 8.907 8.907 0 0 0 8.934 8.934c4.467 0 8.529-3.249 8.529-8.934 0-.528-.081-1.097-.202-1.625z"></path>
                      </svg>
                    </div>
                    Sign in with Google
                  </button>
    
                  <button
                    type="button"
                    className="relative inline-flex items-center justify-center w-full px-4 py-4 text-base font-semibold text-gray-700 transition-all duration-200 bg-white border-2 border-gray-200 rounded-md hover:bg-gray-100 focus:bg-gray-100 hover:text-black focus:text-black focus:outline-none"
                  >
                    <div className="absolute inset-y-0 left-0 p-4">
                      <svg
                        className="w-6 h-6 text-[#2563EB]"
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        fill="currentColor"
                      >
                        <path d="M13.397 20.997v-8.196h2.765l.411-3.209h-3.176V7.548c0-.926.258-1.56 1.587-1.56h1.684V3.127A22.336 22.336 0 0 0 14.201 3c-2.444 0-4.122 1.492-4.122 4.231v2.355H7.332v3.209h2.753v8.202h3.312z"></path>
                      </svg>
                    </div>
                    Sign in with Facebook
                  </button>
                </div>
              </div>
            </div>
    
            <div className="flex items-center justify-center px-4 py-10 sm:py-16 lg:py-24 bg-gray-50 sm:px-6 lg:px-8">
              <div>
                <img
                  className="w-full mx-auto"
                  src={signuppage}
                  alt=""
                />
    
                <div className="w-full max-w-md mx-auto xl:max-w-xl">
                  <h3 className="text-2xl font-bold text-center text-black">
                    Simplify Your Stock Management Today
                  </h3>
                  <p className="leading-relaxed text-center text-gray-500 mt-2.5">
                  Effective stock management is the backbone of a successful business. With the right tools, you can reduce errors,
                   prevent stockouts, and ensure smooth operations that help you meet customer demand seamlessly.
    
                  </p>
    
                  <div className="flex items-center justify-center mt-10 space-x-3">
                    <div className="bg-orange-500 rounded-full w-20 h-1.5"></div>
    
                    <div className="bg-gray-200 rounded-full w-12 h-1.5"></div>
    
                    <div className="bg-gray-200 rounded-full w-12 h-1.5"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      );
}

export default LogIn

// client/src/app/auth/login/login.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrl: './login.component.css',
})
export class LoginComponent {
  imgSrc: string = 'image.png';
  googleImgSrc: string = 'icons8-google-48.png';
  username = '';
  password = '';

  login() {}
}

<div class="flex min-h-screen items-center justify-center bg-gray-100 p-4">
  <div class="flex justify-start w-full bg-white shadow-lg rounded-lg p-8 mx-8">
    <div class="basis-1/3">
      <div class="h-8 w-8 bg-slate-600"></div>
      <h2 class="text-2xl font-semibold text-gray-800 mb-6">Login</h2>
      <p class="text-gray-600 mb-6">See your growth and get support!</p>

      <button
        class="w-full flex items-center justify-center bg-white border border-gray-300 text-gray-600 py-2 rounded-lg shadow-sm mb-4 hover:bg-gray-50 transition duration-150"
      >
        <img [src]="googleImgSrc" alt="Google logo" class="w-6 h-6 mr-2" />
        Sign in with Google
      </button>

      <form (submit)="login()">
        <div class="mb-4">
          <label class="block text-gray-700 font-medium mb-2" for="username"
            >Username*</label
          >
          <input
            type="username"
            id="username"
            class="w-full px-4 py-2 bg-gray-100 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            placeholder="Enter your Username"
            [(ngModel)]="username"
          />
        </div>

        <div class="mb-4">
          <label class="block text-gray-700 font-medium mb-2" for="password"
            >Password*</label
          >
          <input
            type="password"
            id="password"
            class="w-full px-4 py-2 bg-gray-100 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
            placeholder="Minimum 8 characters"
            [(ngModel)]="password"
          />
        </div>

        <div class="flex items-center justify-between mb-6">
          <div>
            <input
              type="checkbox"
              id="rememberMe"
              class="text-blue-600 form-checkbox rounded focus:ring-2 focus:ring-blue-500"
            />
            <label class="ml-2 text-gray-700" for="rememberMe"
              >Remember me</label
            >
          </div>
          <a href="#" class="text-slate-600 hover:underline"
            >Forgot password?</a
          >
        </div>

        <button
          class="w-full bg-slate-900 text-white py-2 rounded-lg hover:bg-slate-700 transition duration-150"
          type="submit"
        >
          Login
        </button>
      </form>

      <p class="text-gray-600 mt-6 text-center">
        Not registered yet?
        <a href="#" class="text-slate-600 hover:underline"
          >Create a new account</a
        >
      </p>
    </div>
    <div class="basis-2/3">
      <img [src]="imgSrc" alt="" />
    </div>
  </div>
</div>
